version: "3.9"
services:
  api:
    container_name: api
    build: ./api
    ports:
      - "8000:80"
  frontend:
    container_name: frontend
    build: ./ui
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
      